version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: ce_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - .docker/mongo/data:/data/db