version: "3.8"
services:
  app:
    build: .
    ports:
      - 5000:5000
  mongodb:
    image: mongo:latest
    container_name: ce_mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - .docker/mongo/data:/data/db
  redis:
    image: redis:latest
    container_name: ce_redis
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - .docker/redis/data:/data
